#include <iostream>
#include <verilated.h>
#include "Vstopwatch_top.h"  // This file is generated by Verilator later

// Current simulation time
vluint64_t main_time = 0;

double sc_time_stamp() {
    return main_time;
}

int main(int argc, char** argv) {
    // 1. Initialize Verilator
    Verilated::commandArgs(argc, argv);
    
    // 2. Instantiate the "Core" (Your Verilog Top Module)
    Vstopwatch_top* top = new Vstopwatch_top;

    // 3. Initial Signal Setup
    top->clk = 0;
    top->rst_n = 0;   // Assert Reset (Active Low)
    top->start = 0;
    top->stop = 0;
    top->reset = 0;
    
    // 4. Simulation Loop
    // We will simulate for 2000 clock cycles
    while (!Verilated::gotFinish() && main_time < 2000) {
        
        // --- Toggle Clock Logic ---
        if ((main_time % 10) == 0) {
            top->clk = !top->clk; // Toggle clock every 10 time units
        }

        // --- User Button Logic (The "Testbench") ---
        
        // Release System Reset after a bit
        if (main_time == 50) { 
            top->rst_n = 1; 
            printf("System Reset Released\n");
        }

        // Press "START" at time 100
        if (main_time == 100) {
            top->start = 1;
            printf("Button Pressed: START\n");
        }
        if (main_time == 120) top->start = 0; // Release button

        // Press "STOP" at time 1000
        if (main_time == 1000) {
            top->stop = 1;
            printf("Button Pressed: STOP\n");
        }
        if (main_time == 1020) top->stop = 0; 

        // Press "RESET" at time 1500
        if (main_time == 1500) {
            top->reset = 1;
            printf("Button Pressed: RESET\n");
        }
        if (main_time == 1520) top->reset = 0;


        // --- Evaluate the Model ---
        // This tells Verilator to calculate all wires based on inputs
        top->eval();

        // --- Read Outputs (Interaction) ---
        // Only print on positive clock edge to avoid spamming
        if (top->clk == 1 && (main_time % 10 == 0)) {
            printf("Time: %lu | Status: %d | Display: %02d:%02d\n", 
                   main_time, top->status, top->minutes, top->seconds);
        }

        main_time++;
    }

    // 5. Cleanup
    top->final();
    delete top;
    return 0;
}
